apiVersion: apps/v1
kind: Deployment
metadata:
  name: protium-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: protium
  template:
    metadata:
      labels:
        app: protium
    spec:
      containers:
      - name: protiumtha
        image: protium
        ports:
        - containerPort: 8080

