apiVersion: apps/v1
kind: Deployment
metadata:
  name: protium-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: protium
  template:
    metadata:
      labels:
        app: protium
    spec:
      containers:
        - name: protium
          image: protium:latest
          ports:
            - containerPort: 8080
